name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure Git
        run: |
          git config --global user.email "leonanorth3@gmail.com"
          git config --global user.name "leonan123"
          git config --global credential.helper
          
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Branch to deploy to
          folder: dist # Folder to deploy
          token: ${{ secrets.GITHUB_TOKEN }}
